### ISSUE TITLE
Support subscript and superscript

### ISSUE THREAD

**Issue by FoxtrotSierra6829** [PupoSDC/chair-flight#168]
![grafik](https://github.com/PupoSDC/chair-flight/assets/50082450/cddd8edf-63f2-4dae-b597-c9842e6ea150)
https://www.chair-flight.com/modules/atpl/questions/QYGMFTZD

**Comment by PupoSDC** [comment]
Ups. Accidentally removed. Will bring it back today or tomorrow.
