### ISSUE TITLE
Add MathJax to support rendering mathematical equations in the explanations

### ISSUE THREAD

**Issue by FoxtrotSierra6829** [PupoSDC/chair-flight#63]

**Comment by FoxtrotSierra6829** [comment]
I see. We'll have to figure something out then

**Comment by PupoSDC** [comment]
TBH, if you are going to start writing explanations and their going to have math in them, I would prioritise having good explanations over payload size. I can fiddle with those optimisations when they become a problem.

**Comment by PupoSDC** [comment]
Some progress has been made here. Mathjax is now supported on Serverside markdown. 
Client side markdown still does not have this, but the goal should be to find a way to move most, if not all, markdown generation to server side. 

It's a WIP that overlaps with https://github.com/PupoSDC/chair-flight/issues/103

**Comment by PupoSDC** [comment]
Mathjax is now fully supported in explanations. Some work is still needed to put it everywhere else, but it falls under

https://github.com/PupoSDC/chair-flight/issues/103
