### ISSUE TITLE
Flashcard answers not matching questions

### ISSUE THREAD

**Issue by FoxtrotSierra6829** [PupoSDC/chair-flight#69]
<details>
<summary>Ryanair</summary>

Found only these to not be matching
![grafik](https://github.com/PupoSDC/chair-flight/assets/50082450/1e9aeda4-0a17-401a-adc6-b7c0c8f3ee1b)
![grafik](https://github.com/PupoSDC/chair-flight/assets/50082450/b4ba3199-3d0d-45fb-888b-14af8847e8d1)

</details>

<details><summary>Seneca</summary>

Most questions affected
![grafik](https://github.com/PupoSDC/chair-flight/assets/50082450/0a0f868f-d60c-405e-ad91-92f69ee62207)

</details>

**Comment by PupoSDC** [comment]
These are quite funny 😅 

I'll fix, or at the very least replace with a placeholder.
